language: none
services:
  - docker

before_script: 
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD

script:
  - echo "containers building..."
  - ( cd deploy ; docker-compose build )

deploy:
- provider: script
  script: bash deploy/aws.sh
  on:
    branch: onyxchain-v2 